import { expect, type Page } from "@playwright/test";

// These drive the real forms rather than calling the API directly, because the
// point of an end to end test is that the whole path works: the form, the
// Server Action, the API, the cookie, and the redirect afterwards.

/**
 * A fresh account per run. The API has no way to delete a user, so a fixed
 * address would collide with itself on the second run.
 *
 * Registration is rate limited to 5 per hour per IP, so this is used once, by
 * register.spec.ts, and never inside a helper that other tests call.
 */
export function uniqueEmail(prefix = "e2e"): string {
  return `${prefix}.${Date.now()}.${Math.floor(Math.random() * 1000)}@example.com`;
}

export async function loginAs(page: Page, email: string, password: string) {
  await page.goto("/login");
  await page.getByLabel("Email").fill(email);
  await page.getByLabel("Password").fill(password);
  await page.getByRole("button", { name: /log in/i }).click();

  await page.waitForURL(/\/dashboard/);
}

export async function logout(page: Page) {
  await page.getByRole("button", { name: /log out/i }).click();
  await page.waitForURL("/");
}

/**
 * Walks the booking flow and returns the booking reference.
 *
 * Picks the first free time rather than a fixed one, because previous runs of
 * this very test will have taken slots, and a hardcoded time would start
 * failing after a while for a reason that looks like a bug.
 */
export async function bookFirstFreeSlot(page: Page, doctorId = "1") {
  // Tries a few slots, not just one. The API has been seen to offer a time as
  // free and then refuse it on submit, and the app correctly shows "that time
  // is no longer available" rather than pretending it worked. A real person
  // would pick another time, so the test does too. Without this the suite
  // failed intermittently for a reason that was not a bug in the app.
  const MAX_ATTEMPTS = 3;

  for (let attempt = 0; attempt < MAX_ATTEMPTS; attempt++) {
    await page.goto(`/book/${doctorId}`);

    // Only a free time is a link; a taken one renders as a disabled button, so
    // there is nothing to filter out here.
    const free = page.locator('a[href*="&time="]');
    await expect(
      free.first(),
      "no free appointment times were offered, so the doctor may have no working hours",
    ).toBeVisible();

    const count = await free.count();
    if (attempt >= count) break;
    await free.nth(attempt).click();

    await expect(page.getByRole("heading", { name: "Confirm your appointment" })).toBeVisible();

    await page.getByLabel("Reason for visit").fill("End to end test booking");
    await page.getByLabel(/I agree/).check();
    await page.getByRole("button", { name: "Confirm booking" }).click();

    // Whichever of the two arrives first: the confirmation page, or the form
    // coming back with an error. Waiting only for the URL would sit there for
    // the full timeout when the slot was refused.
    const problem = page.getByRole("alert").filter({ hasText: /no longer available|just booked/i });
    await expect(async () => {
      expect((await problem.count()) > 0 || /\/confirmed/.test(page.url())).toBe(true);
    }).toPass({ timeout: 15_000 });

    if (/\/confirmed/.test(page.url())) {
      // The reference is generated by the API, in the form CC-NNNN-XXX, and the
      // confirmation page is where the patient is told it.
      const reference = await page
        .locator("p", { hasText: /^CC-\d+-[A-Z]+$/ })
        .first()
        .textContent();

      return (reference ?? "").trim();
    }
  }

  throw new Error(
    `every one of the first ${MAX_ATTEMPTS} free slots was refused on submit, which means the availability the API reports does not match what it will accept`,
  );
}

/**
 * Cancels the appointment whose detail page is currently open, and waits for
 * the page to come back showing it cancelled.
 *
 * Tests that book call this at the end, so a run cleans up the records it
 * created instead of filling the shared database with test bookings.
 */
export async function cancelAppointment(page: Page) {
  await page.getByRole("button", { name: "Cancel", exact: true }).first().click();

  const dialog = page.getByRole("dialog");
  await expect(dialog).toBeVisible();
  await dialog.getByRole("button", { name: "Yes, cancel it" }).click();

  // The cancel controls disappear once it is cancelled, which is the signal
  // that the Server Action finished and the page revalidated.
  await expect(dialog).toBeHidden();
}
